service: gerenciarPedidos # service para gerenciar pedidos 

provider:
  name: aws
  runtime: nodejs8.10

functions:
    
  registrarPedido:  
    handler: handler.registrarPedido
    events: # evento de registrar pedido
      - http:
          path: gerenciarPedidos/registrarPedido/{pedido}
          method: post
          cors: true
          request:
            parameters:
              paths:
                pedido: true
          

resources:  # recursos
  Resources:
    pedidosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pedidosTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1          
plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
